# Generated by Django 5.2.9 on 2025-12-14 14:00

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_user_gender"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="full_name",
            field=models.CharField(
                default=users.models.generate_random_name, max_length=50
            ),
        ),
    ]
